const express = require("express");
const router = express.Router();
const ManPowerRequest = require("../WorkService/Model_RequestManPower.cjs");

router.post("/GetFactory", ManPowerRequest.GetFactory);
router.post("/GetFactoryIssue", ManPowerRequest.GetFactoryIssue);
router.post("/GetFactoryMasterlist", ManPowerRequest.GetFactoryMasterlist);
router.post("/GetDepartment", ManPowerRequest.GetDepartment);
router.post("/GetDepartmentIssue", ManPowerRequest.GetDepartmentIssue);
router.post("/GetPosition", ManPowerRequest.GetPosition);
router.post("/GetJobGrade", ManPowerRequest.GetJobGrade);
router.post("/GetEmployeeType", ManPowerRequest.GetEmployeeType);
router.post("/GetForDept", ManPowerRequest.GetForDept);
router.post("/GetEducation", ManPowerRequest.GetEducation);
router.post("/GetCourse", ManPowerRequest.GetCourse);
router.post("/GetRequestJobGrade", ManPowerRequest.GetRequestJobGrade);
router.post("/GetField", ManPowerRequest.GetField);
router.post("/GetEnglish", ManPowerRequest.GetEnglish);
router.post("/GetDataPersonByIDCode", ManPowerRequest.GetDataPersonByIDCode);
router.post("/GetDeptByCC", ManPowerRequest.GetDeptByCC);
router.post("/GenRunNo", ManPowerRequest.GenRunNo);
router.post("/FindStatusCodebyDesc", ManPowerRequest.FindStatusCodebyDesc);
router.post("/InsGenNoRequest", ManPowerRequest.InsGenNoRequest);
router.post("/InsGenNoRequest2", ManPowerRequest.InsGenNoRequest2);
router.post("/GetDepartmentManager", ManPowerRequest.GetDepartmentManager);
router.post("/GetHrManager", ManPowerRequest.GetHrManager);
router.post("/GetFMDM", ManPowerRequest.GetFMDM);
router.post("/SaveDraft", ManPowerRequest.SaveDraft);
router.post("/InsPerson", ManPowerRequest.InsPerson);
router.post("/InsPersonDetail", ManPowerRequest.InsPersonDetail);
router.post("/SearchManPower", ManPowerRequest.SearchManPower);
router.post("/GetDataEdit", ManPowerRequest.GetDataEdit);
router.post("/GetDataDetailStep1", ManPowerRequest.GetDataDetailStep1);
router.post("/GetDataPerson", ManPowerRequest.GetDataPerson);
router.post("/GetDataPersonDetail", ManPowerRequest.GetDataPersonDetail);
router.post("/DelDataPersonDetail", ManPowerRequest.DelDataPersonDetail);
router.post("/GetEmail", ManPowerRequest.GetEmail);
router.post("/UpdateApprove", ManPowerRequest.UpdateApprove);
router.post("/UpdateReject", ManPowerRequest.UpdateReject);
router.post("/GetConditionForClose", ManPowerRequest.GetConditionForClose);
router.post("/SaveDarftHr", ManPowerRequest.SaveDarftHr);
router.post("/UpdateUserJoin", ManPowerRequest.UpdateUserJoin);
router.post("/GetHrStarff", ManPowerRequest.GetHrStarff);
router.post("/GetStatusSearch", ManPowerRequest.GetStatusSearch);
router.post("/SearchManPowerApprove", ManPowerRequest.SearchManPowerApprove);
router.post("/UploadSub", ManPowerRequest.UploadSub);
router.post("/HomeStatusCountManPower", ManPowerRequest.HomeStatusCountManPower);
router.post("/UploadHr", ManPowerRequest.UploadHr);
router.post("/GetDepartmentMasterList", ManPowerRequest.GetDepartmentMasterList);
router.post("/GetUserJoinHr", ManPowerRequest.GetUserJoinHr);

module.exports = router;
